// <auto-generated />
using ClockInClockOut.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClockInClockOut.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClockInClockOut.Data.Employee", b =>
                {
                    b.Property<int>("IdNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNumber"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClockedIN")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNumber");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            IdNumber = 1995,
                            FirstName = "Hensley",
                            IsClockedIN = false,
                            LastName = "Wint"
                        },
                        new
                        {
                            IdNumber = 2020,
                            FirstName = "Jason",
                            IsClockedIN = false,
                            LastName = "Choi"
                        },
                        new
                        {
                            IdNumber = 1234,
                            FirstName = "Max",
                            IsClockedIN = false,
                            LastName = "Samuel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
